/* COSA scroll home v1. Existing Imweb content is preserved beneath a scoped presentation. */
(function () {
  if (location.pathname !== '/' || /(?:mode|bmode|preview|admin)=/.test(location.search)) return;
  function mount() {
    var original = document.getElementById('s202609015b18c1e667e5c');
    if (!original || document.getElementById('cosa-scroll-home')) return;
    var root = document.createElement('main'); root.id = 'cosa-scroll-home';
    var base = 'https://cdn.imweb.me/thumbnail/20260901/';
    var photos = ['1834ee6ae7574','23d6521e13ec7','3d677debcf3ad','7847cd2fc9f31','dba8f4f8457dc','c7a2e1f75b69b','d87cb69786a82'];
    function photo(i,alt,cls,eager) {return '<img class="'+(cls||'')+'" src="'+base+photos[i]+'.png" alt="'+alt+'" '+(eager?'fetchpriority="high"':'loading="lazy"')+' decoding="async" width="1920" height="1080">';}
    root.innerHTML = '<nav class="cs-nav" aria-label="제품 탐색"><a href="#cs-top" class="cs-wordmark">COSA<span>CONVERTIBLE PRO</span></a><a class="cs-buy" href="/17/?idx=4">제품 알아보기 <span aria-hidden="true">↗</span></a></nav>'+
      '<section class="cs-hero" id="cs-top"><p class="cs-eyebrow">ONE BAG. EVERY MODE.</p><h1>하나의 가방.<br><span>가능성은 네 가지.</span></h1><p class="cs-lead">일하는 순간부터, 떠나는 순간까지.<br>당신의 하루에 맞춰 달라지는 COSA.</p>'+photo(0,'COSA Convertible Pro 블랙 가방 정면','cs-hero-image',true)+'<a class="cs-scroll" href="#cs-transform">스크롤하여 살펴보기 <span aria-hidden="true">↓</span></a></section>'+
      '<section class="cs-transform" id="cs-transform" aria-label="가방의 다양한 모습"><div class="cs-stage"><div class="cs-stage-copy"><p class="cs-eyebrow">BUILT TO CHANGE</p><h2>당신의 하루는<br>한 가지가 아니니까.</h2><p>브리프케이스. 토트백. 메신저백. 백팩.<br>하나의 가방에 담은 네 가지 가능성.</p></div><div class="cs-sequence">'+photo(0,'가방 정면','cs-frame is-active',true)+photo(1,'가방의 측면과 구조','cs-frame',true)+photo(2,'가방의 스트랩과 뒷면','cs-frame',true)+'</div><div class="cs-stage-bottom"><span class="cs-frame-label">01 / FRONT</span><div class="cs-track" aria-hidden="true"><i></i></div><span>CONVERTIBLE PRO</span></div></div></section>'+
      '<section class="cs-life cs-reveal"><p class="cs-eyebrow">MOVE YOUR WAY</p><h2>손에 가볍게.<br>어깨에 자연스럽게.</h2><p class="cs-lead">일과 여행, 일상의 경계에서.<br>지금 필요한 방식으로 들어보세요.</p><div class="cs-life-grid"><figure>'+photo(4,'손으로 든 COSA 가방')+'<figcaption><span>01</span> Carry it.</figcaption></figure><figure>'+photo(5,'어깨에 착용한 COSA 가방')+'<figcaption><span>02</span> Wear it.</figcaption></figure><figure>'+photo(6,'COSA 가방을 착용한 측면')+'<figcaption><span>03</span> Make it yours.</figcaption></figure></div></section>'+
      '<section class="cs-detail cs-reveal"><div class="cs-detail-copy"><p class="cs-eyebrow">ROOM FOR YOUR DAY</p><h2>필요한 것들을.<br>당신의 방식대로.</h2><p>밖에서는 간결하게.<br>안에서는 하루의 도구들을 담을 수 있도록.</p></div>'+photo(3,'가방 내부 수납과 소지품 디테일')+'</section>'+
      '<section class="cs-finale cs-reveal"><p class="cs-eyebrow">COSA / CONVERTIBLE PRO</p><h2>다음 순간도,<br>함께.</h2>'+photo(1,'COSA Convertible Pro 제품 측면')+'<a class="cs-primary" href="/17/?idx=4">제품 알아보기 <span aria-hidden="true">↗</span></a><p>하나의 가방. 당신만의 모든 방식.</p></section>';
    var css = document.createElement('style');css.id='cosa-scroll-home-css';css.textContent=`
#cosa-scroll-home{--ink:#171719;--muted:#747478;--paper:#f5f5f7;--progress:0;color:var(--ink);background:#fff;font-family:Pretendard,-apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo",sans-serif;overflow:clip;width:100%;text-align:center;line-height:1.5}
#cosa-scroll-home *{box-sizing:border-box}#cosa-scroll-home a{color:inherit;text-decoration:none}#cosa-scroll-home img{display:block;width:100%;height:auto}#cosa-scroll-home h1,#cosa-scroll-home h2,#cosa-scroll-home p,#cosa-scroll-home figure{margin:0}#cosa-scroll-home h1,#cosa-scroll-home h2{font-weight:700;letter-spacing:-.055em;line-height:1.1;word-break:keep-all}#cosa-scroll-home section{scroll-margin-top:80px}
#cosa-scroll-home .cs-nav{position:relative;z-index:3;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:22px max(6vw,24px);border-top:1px solid #ececee;border-bottom:1px solid #ececee;background:#fffffff0;font-size:13px}
#cosa-scroll-home .cs-wordmark{font-weight:800;font-size:23px;letter-spacing:-.04em}#cosa-scroll-home .cs-wordmark span{font-size:10px;font-weight:500;letter-spacing:.08em;margin-left:18px;color:var(--muted)}#cosa-scroll-home .cs-buy{font-size:12px;font-weight:600}#cosa-scroll-home .cs-buy span{margin-left:15px}
#cosa-scroll-home .cs-eyebrow{font-size:11px;font-weight:600;letter-spacing:.19em;margin-bottom:25px;color:var(--muted)}#cosa-scroll-home .cs-hero{padding:100px 24px 44px;background:#fff}#cosa-scroll-home h1{font-size:clamp(45px,6.3vw,92px)}#cosa-scroll-home h1 span{color:#86868b}#cosa-scroll-home .cs-lead{font-size:18px;line-height:1.65;color:var(--muted);margin-top:26px;letter-spacing:-.025em}#cosa-scroll-home .cs-hero-image{max-width:1200px;margin:-5px auto -28px;transform:scale(var(--hero-scale,1));will-change:transform}#cosa-scroll-home .cs-scroll{display:inline-flex;gap:20px;color:var(--muted);font-size:11px;letter-spacing:.04em}
#cosa-scroll-home .cs-transform{height:230vh;position:relative;background:var(--paper)}#cosa-scroll-home .cs-stage{height:100svh;min-height:600px;max-height:1100px;position:sticky;top:0;display:flex;flex-direction:column;justify-content:center;padding:55px 6vw 32px;overflow:hidden}#cosa-scroll-home .cs-stage h2{font-size:clamp(35px,4.3vw,64px)}#cosa-scroll-home .cs-stage-copy>p:last-child{color:var(--muted);font-size:15px;line-height:1.7;margin-top:20px}#cosa-scroll-home .cs-sequence{position:relative;flex:1;min-height:210px;width:100%;max-width:1080px;align-self:center;mix-blend-mode:multiply}#cosa-scroll-home .cs-frame{position:absolute;inset:0;height:100%;object-fit:contain;opacity:0;transition:opacity .55s ease,transform .8s ease;transform:scale(.92)}#cosa-scroll-home .cs-frame.is-active{opacity:1;transform:scale(1)}#cosa-scroll-home .cs-stage-bottom{display:flex;justify-content:space-between;align-items:center;gap:25px;font-size:10px;letter-spacing:.13em;color:var(--muted)}#cosa-scroll-home .cs-track{width:35%;height:2px;background:#d8d8dc;overflow:hidden}#cosa-scroll-home .cs-track i{display:block;height:100%;background:#191919;transform-origin:left;transform:scaleX(var(--progress))}
#cosa-scroll-home .cs-life{padding:140px 5vw 100px}#cosa-scroll-home .cs-life h2,#cosa-scroll-home .cs-detail h2{font-size:clamp(38px,4.9vw,72px)}#cosa-scroll-home .cs-life-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:75px auto 0;max-width:1440px}#cosa-scroll-home .cs-life figure{background:var(--paper);border-radius:22px;overflow:hidden;text-align:left;padding-bottom:28px}#cosa-scroll-home .cs-life figure img{aspect-ratio:4/5;object-fit:cover;mix-blend-mode:multiply}#cosa-scroll-home figcaption{padding:0 25px;font-size:18px;font-weight:600;letter-spacing:-.02em}#cosa-scroll-home figcaption span{font-size:10px;margin-right:18px;color:var(--muted)}
#cosa-scroll-home .cs-detail{background:#171719;color:#fff;display:grid;grid-template-columns:1fr 1.25fr;align-items:center;text-align:left;gap:50px;padding:120px 7vw}#cosa-scroll-home .cs-detail-copy>p:last-child{color:#a8a8af;font-size:17px;line-height:1.7;margin-top:30px}#cosa-scroll-home .cs-detail img{border-radius:18px}#cosa-scroll-home .cs-detail .cs-eyebrow{color:#a8a8af}
#cosa-scroll-home .cs-finale{padding:130px 24px 100px}#cosa-scroll-home .cs-finale h2{font-size:clamp(55px,7.2vw,105px)}#cosa-scroll-home .cs-finale img{max-width:960px;margin:0 auto -25px}#cosa-scroll-home .cs-primary{display:inline-flex;align-items:center;gap:45px;background:#171719;color:#fff;padding:17px 27px;border-radius:32px;font-size:14px}#cosa-scroll-home .cs-finale>p:last-child{font-size:12px;color:var(--muted);margin-top:24px}
#cosa-scroll-home .cs-reveal{opacity:1}#cosa-scroll-home.cs-motion .cs-reveal{opacity:0;transform:translateY(35px);transition:opacity .9s ease,transform .9s ease}#cosa-scroll-home.cs-motion .cs-reveal.is-visible{opacity:1;transform:none}#cosa-scroll-home a:focus-visible{outline:3px solid #3979ec;outline-offset:6px}
@media(max-width:767px){#cosa-scroll-home .cs-nav{padding:18px 20px}#cosa-scroll-home .cs-wordmark span{display:none}#cosa-scroll-home .cs-hero{padding:65px 18px 42px}#cosa-scroll-home h1{font-size:48px}#cosa-scroll-home .cs-lead{font-size:15px}#cosa-scroll-home .cs-hero-image{width:150%;max-width:none;margin:10px -25% -5px}#cosa-scroll-home .cs-stage{padding:45px 20px 30px;min-height:560px}#cosa-scroll-home .cs-transform{height:200vh}#cosa-scroll-home .cs-stage h2{font-size:37px}#cosa-scroll-home .cs-stage-copy>p:last-child{font-size:13px}#cosa-scroll-home .cs-sequence{width:165%;max-width:none}#cosa-scroll-home .cs-stage-bottom{font-size:8px;gap:12px}#cosa-scroll-home .cs-stage-bottom>span:last-child{display:none}#cosa-scroll-home .cs-track{width:50%}#cosa-scroll-home .cs-life{padding:85px 20px 65px}#cosa-scroll-home .cs-life-grid{grid-template-columns:1fr;gap:20px;margin-top:45px}#cosa-scroll-home .cs-life figure img{aspect-ratio:4/3}#cosa-scroll-home .cs-life figure{padding-bottom:24px}#cosa-scroll-home .cs-detail{grid-template-columns:1fr;gap:35px;padding:70px 24px}#cosa-scroll-home .cs-detail h2{font-size:39px}#cosa-scroll-home .cs-detail-copy>p:last-child{font-size:15px}#cosa-scroll-home .cs-finale{padding:80px 20px}#cosa-scroll-home .cs-finale img{width:150%;max-width:none;margin:10px -25% 0}#cosa-scroll-home .cs-eyebrow{font-size:9px}}
@media(prefers-reduced-motion:reduce){#cosa-scroll-home .cs-transform{height:auto}#cosa-scroll-home .cs-stage{position:relative;height:auto;min-height:700px}#cosa-scroll-home .cs-frame{transition:none}#cosa-scroll-home .cs-reveal{opacity:1!important;transform:none!important;transition:none!important}#cosa-scroll-home .cs-hero-image{transform:none}}
`;
    document.head.appendChild(css);original.parentNode.insertBefore(root,original);
    // Hide the old presentation only after the replacement exists. Removing this script restores it on reload.
    original.hidden = true; original.style.setProperty('display','none','important');
    var reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    if(!reduced && 'IntersectionObserver' in window){root.classList.add('cs-motion');var observer=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}});},{threshold:.08});root.querySelectorAll('.cs-reveal').forEach(function(el){observer.observe(el);});}
    var stage=root.querySelector('.cs-transform'),frames=root.querySelectorAll('.cs-frame'),label=root.querySelector('.cs-frame-label'),scheduled=false;
    function update(){scheduled=false;var r=stage.getBoundingClientRect(),p=Math.max(0,Math.min(1,-r.top/Math.max(1,stage.offsetHeight-innerHeight))),n=Math.min(2,Math.floor(p*3));root.style.setProperty('--progress',p);frames.forEach(function(f,i){f.classList.toggle('is-active',i===n);});label.textContent=['01 / FRONT','02 / PERSPECTIVE','03 / REVERSE'][n];var hero=root.querySelector('.cs-hero').getBoundingClientRect();root.style.setProperty('--hero-scale',String(1+Math.min(.09,Math.max(0,-hero.top/8000))));}
    if(!reduced){addEventListener('scroll',function(){if(!scheduled){scheduled=true;requestAnimationFrame(update);}},{passive:true});addEventListener('resize',update);update();}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
